## Example Config file
baseURL: "https://nfdz.dev"
theme: "terminalcv"
title: "nfdz"

params:
  version: 'v3.27.3+hotfix.9'
  description: "Software engineer specialized in mobile technologies."
  prompt:
    core:
      text: "user@nfdz.dev"
      color: '#D2FF72'
      before: '['
      beforeColor: '#D2FF72'
      after: '\]'
      afterColor: '#D2FF72'
      # separator: '-'
    separator:
      text: ":"
      separatorColor: '#D2FF72'
    path: 
      # before: '['
      # beforeColor: '#D2FF72'
      text: '~'
      color: '#D2FF72'
      # after: '\]'
      # afterColor: '#D2FF72'
    extra:
      text: "$ "
      color: '#D2FF72'

  # promptColor: grey
  # promptSimbols: ":~$"
  # promptSimbolsColor: grey
  # startxLocation: https://example.com
  # useLess: true
  exitLocation: 'about:blank'
  source: true
  #use a ‎ (blank character) if your first character of the ascii art is a whitespace
  greeting: | 
    ‎
                 .o88o.       .o8            
                 888 `"      "888            
    ooo. .oo.   o888oo   .oooo888    oooooooo
    `888P"Y88b   888    d88' `888   d'""7d8P 
     888   888   888    888   888     .d8P'  
     888   888   888    888   888   .d8P'  .P
    o888o o888o o888o   `Y8bod88P" d8888888P                                     

    Welcome! Nice to meet you. Use this terminal to learn more about me and my work.

    Type 'help' for a list of available commands


  whois: 
    # settings:
    #   useLess: true
    details:
      name: "Noé Fernández"
      profession: "Software Engineer"
      location: "Europe"
      email: "hey@nfdz.dev"
      homelink: "https://nfdz.dev"
      description: |
              I am an experienced, reliable, communicative, and team player software engineer. I have specialized in mobile development throughout my professional experience. I am always looking for challenging, intellectually stimulating, creative environments where I can apply my knowledge and skills for continuous growth and improvement.

  social:
    # settings:
    #   useLess: true
    #   hideName: true
    details:
    - name: "github"
      url: "https://github.com/nfdz"
    - name: "x/twitter"
      url: "https://x.com/nfdzdev"
    - name: "Email"
      url: "hey@nfdz.dev"

  work:
    # settings:
    #   useLess: true
    details:
    - jobTitle: Mobile Software Engineer
      # color: red
      # company: 'Freelance & Entrepreneur' 
      # location: Spain
      date: 2023 - Present
      description: Flutter, Mobile, Web, MacOS, Windows, Google Play, App Store, ChatGPT, RevenueCat, Stripe.

    - jobTitle: Mobile Software Engineer
      date: 2020  - 2023
      description: Kotlin Multiplatform, Flutter, Android, iOS, tvOS, CircleCI, React Native, Unity.

    - jobTitle: Flutter Software Engineer
      date: 2019 - 2020
      description: Flutter, Android, iOS, Scrum, Agile, Jenkins, Grafana, Countly, Here Maps.

    - jobTitle: Flutter Developer
      date: 2018 - 2019
      description: Flutter, Dart, Kotlin, Android, iOS, Firebase, Facebook, Google Maps.

    - jobTitle: Android Software Engineer
      date: 2017 - 2018
      description: Android, CI with VSTS, Firebase, Google Fit, Bluetooth, NFC, Azure Notifications Hub, Azure IoT, Facebook.

    - jobTitle: Satellite Software Engineer
      date: 2015 - 2016
      description: Java, Eclipse RCP, Python, Protocol buffers, CORBA, HornetQ, C++, JUnit.

  education:
    details:
    - courseName: Flutter App Development Bootcamp
      date: 2019
      description: App Brewery & Google Flutter Team

    - courseName: Associate Android Developer
      date: 2017
      description: Google

    - courseName: Leadership Skills & Team Management
      date: 2015
      description: University

    - courseName: Bachelor's Degree in Telematics. 
      date: 2010 - 2014
      description: University

  skills:
    # settings:
    #   useLess: true
    details:
    - name: Dart
      percentage: 100
      # color: blue
      # description: you can add a description

    - name: Kotlin
      percentage: 100

    - name: Java
      percentage: 80

    - name: Swift
      percentage: 60

    - name: C#
      percentage: 50

    - name: JavaScript
      percentage: 50

    - name: Python
      percentage: 30

    - name: C++
      percentage: 30

  platforms:
    # settings:
    #   useLess: true
    details:
    - name: Android
      percentage: 100
      # color: red
      #description:

    - name: iOS
      percentage: 80

    - name: Linux (Backend)
      percentage: 80

    - name: Firebase
      percentage: 70

    - name: MacOS
      percentage: 70

    - name: MacOS
      percentage: 70

    - name: Linux (Frontend)
      percentage: 50

    - name: Windows
      percentage: 40

  frameworks:
    # settings:
    #   useLess: true
    details:
    - name: Flutter
      percentage: 100
      # color: red
      #description:

    - name: Kotlin Multiplatform
      percentage: 100

    - name: Jetpack Compose
      percentage: 80

    - name: Material UI
      percentage: 70

    - name: Realm
      percentage: 70

    - name: SQLite
      percentage: 70

    - name: Cloud Functions
      percentage: 60

    - name: Unity
      percentage: 40

  languages:
    # settings:
    #   useLess: true
    details:
    - name: Spanish
      # color: Blue
      #description: 
      percentage: 100

    - name: English
      percentage: 80

    - name: Portuguese
      percentage: 60

  projects:
    # settings:
    #   useLess: true
    details:
    - title: Rapidrive
      # color: red
      date: 2024
      link: https://rapidrive.app
      description: Unlimited cloud storage powered by your own devices. Made with Flutter.

    - title: Cryptool
      date: 2021
      link: https://github.com/nfdz/Cryptool
      description: Open source cryptography Android application.

    - title: Club App
      date: 2020
      link: https://github.com/nfdz/ClubApp
      description: Android application to manage and loyalty your club members.

    - title: Findoor
      date: 2019
      link: https://github.com/nfdz/Findoor
      description: Android Library for Indoor Wi-Fi Navigation.

    - title: Interactive Tree Stand
      date: 2018
      link: https://nfdz.dev/interactive-tree.jpeg
      description: Arduino and Raspberry Pi advertising stand for a fair.

    - title: Permissions Watcher
      date: 2017
      link: https://github.com/nfdz/PermissionsWatcher
      description: Android permissions manager application.

  # certifications:
  #   # settings:
  #   #   useLess: true
  #   details:
  #   - certName: Example Cert
  #     company: Example Certifying Company
  #     date: Date of Completion
  #     badge: https://www.link.to.badge
  #     #description: Lorem Ipsum
  
  misc: 
    # settings:
    #   useLess: true
    commandName: hello
    title: "greets the visitor"
    titleColor: Lavender
    content: |
          Hi, how's everything going? :D 
          Maybe you'd like to try a different way to say hello, try using 'contact'.
    contentColor: orange
