name: CD

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    if: "(github.ref == 'refs/heads/master')"
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Config Git
        env:
          githubActor: ${{ github.actor }}
        run: git config --global user.name "$githubActor" && git config --global user.email "$githubActor@github"
      - name: Build
        run: hugo && mv public ${{ runner.temp }}/public
      - name: Checkout Release
        run: git fetch origin && git checkout "origin/release/master"
      - name: Prepare
        run: rm -rf docs && mv ${{ runner.temp }}/public docs
      - name: Publish
        run: git add docs && git commit -m "[CD] Release" && git push origin HEAD:release/master
        