name: CD

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    if: "(github.ref == 'refs/heads/master')"
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.140.2'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Config Git
        env:
          githubActor: ${{ github.actor }}
        run: git config --global user.name "$githubActor" && git config --global user.email "$githubActor@github"
      - name: Checkout Release
        run: git fetch origin && git checkout "origin/release/master" && git merge -X theirs "origin/master" --allow-unrelated-histories
      - name: Build
        run: hugo
      - name: Prepare
        run: rm -rf docs && mv public docs
      - name: Publish
        run: git add docs && git commit -m "[CD] Release" && git push origin HEAD:release/master
        